
language: node_js
node_js:
  - 5.1.0
before_script:
  - npm install -g electron-builder
  - npm install -g electron-packager

script:
  - electron-packager ./ --platform=mas --arch=x64

branches:
  only:
    - master